apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeblossom-cloud-containers-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codeblossom-cloud-containers-ui
  template:
    metadata:
      labels:
        app: codeblossom-cloud-containers-ui
    spec:
      containers:
        - name: codeblossom-cloud-containers-ui
          image: codeblossom-cloud-containers-ui:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: NodePort
  selector:
    app: codeblossom-cloud-containers-ui
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeblossom-cloud-containers-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeblossom-cloud-containers-api
  template:
    metadata:
      labels:
        app: codeblossom-cloud-containers-api
    spec:
      containers:
        - name: codeblossom-cloud-containers-api
          image: codeblossom-cloud-containers-api:latest
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: codeblossom-cloud-containers-api
  ports:
    - port: 30001
      targetPort: 3001